// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRyZXSd2XMSOxg2kM-bxQ7uWO7RfBmYWM',
    appId: '1:506745409286:web:cecca41cc1c3a7bd9b9887',
    messagingSenderId: '506745409286',
    projectId: 'trivia-pokayoke',
    authDomain: 'trivia-pokayoke.firebaseapp.com',
    storageBucket: 'trivia-pokayoke.firebasestorage.app',
    measurementId: 'G-B2QKCE76PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAix7Frlh-NHZi1KWcUE4YaBSr0VJX7VM',
    appId: '1:506745409286:android:d53d1d6f14eecbe49b9887',
    messagingSenderId: '506745409286',
    projectId: 'trivia-pokayoke',
    storageBucket: 'trivia-pokayoke.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Mr4JBjDLf4fF9SyZYIVgLplGHeqALiQ',
    appId: '1:506745409286:ios:60895457f10906cd9b9887',
    messagingSenderId: '506745409286',
    projectId: 'trivia-pokayoke',
    storageBucket: 'trivia-pokayoke.firebasestorage.app',
    iosBundleId: 'com.example.triviaPokayoke',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Mr4JBjDLf4fF9SyZYIVgLplGHeqALiQ',
    appId: '1:506745409286:ios:60895457f10906cd9b9887',
    messagingSenderId: '506745409286',
    projectId: 'trivia-pokayoke',
    storageBucket: 'trivia-pokayoke.firebasestorage.app',
    iosBundleId: 'com.example.triviaPokayoke',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRyZXSd2XMSOxg2kM-bxQ7uWO7RfBmYWM',
    appId: '1:506745409286:web:46e8d03e76a9a1b69b9887',
    messagingSenderId: '506745409286',
    projectId: 'trivia-pokayoke',
    authDomain: 'trivia-pokayoke.firebaseapp.com',
    storageBucket: 'trivia-pokayoke.firebasestorage.app',
    measurementId: 'G-FJZZE9LBH9',
  );
}
